
CREATE FUNCTION FN_COMPARA_RANGE_TIMES (@TEMPO_INICIO TIME(1), @TEMPO_FIM TIME(1), @TEMPO_INICIO_COMP TIME(1), @TEMPO_FIM_COMP TIME(1))
RETURNS BIT

BEGIN

DECLARE	@FLG_TEMPO_SUBCONJUNTO	BIT
DECLARE @TABELA_TEMPO			TABLE (SEQ INT, TEMPO TIME(1))
DECLARE @TABELA_TEMPO_COMP		TABLE (SEQ INT, TEMPO TIME(1))

--Deixa por padrão setado em zero
SET @FLG_TEMPO_SUBCONJUNTO = 0

----Seta Tempo de Referencia
--SET @TEMPO_INICIO	= '22:00:00'
--SET @TEMPO_FIM		= '02:00:00'

----Seta Tempo Comparativo
--SET @TEMPO_INICIO_COMP	= '00:00:00'
--SET @TEMPO_FIM_COMP		= '16:00:00'

SET @TEMPO_FIM		= CASE WHEN @TEMPO_INICIO = @TEMPO_FIM			 THEN DATEADD(MI, -1, @TEMPO_FIM)		ELSE @TEMPO_FIM		 END
SET @TEMPO_FIM_COMP = CASE WHEN @TEMPO_INICIO_COMP = @TEMPO_FIM_COMP THEN DATEADD(MI, -1, @TEMPO_FIM_COMP)	ELSE @TEMPO_FIM_COMP END


--Cria tabela de tempos de referencia
BEGIN
	WITH CTE1A AS (
	SELECT SEQ = 1, TEMPO = @TEMPO_INICIO
	UNION ALL
	SELECT SEQ = SEQ + 1, TEMPO = DATEADD(MI, 1,  TEMPO)
		FROM CTE1A
		WHERE TEMPO < CASE WHEN @TEMPO_INICIO <= @TEMPO_FIM THEN @TEMPO_FIM
						   WHEN TEMPO BETWEEN '00:00:00' AND @TEMPO_FIM THEN @TEMPO_FIM 
						   WHEN TEMPO >= @TEMPO_INICIO THEN '23:59:59' END
	)
	INSERT INTO @TABELA_TEMPO (SEQ, TEMPO)
	SELECT SEQ, TEMPO
		FROM CTE1A
		OPTION (MAXRECURSION 32767)
END

--Cria tabela de tempos comparativo
BEGIN
	WITH CTE1B AS (
	SELECT SEQ = 1, TEMPO = @TEMPO_INICIO_COMP
	UNION ALL
	SELECT SEQ = SEQ + 1, TEMPO = DATEADD(MI, 1,  TEMPO)
		FROM CTE1B
		WHERE TEMPO < CASE WHEN @TEMPO_INICIO_COMP <= @TEMPO_FIM_COMP			THEN @TEMPO_FIM_COMP
						   WHEN TEMPO BETWEEN '00:00:00' AND @TEMPO_FIM_COMP	THEN @TEMPO_FIM_COMP 
						   WHEN TEMPO >= @TEMPO_INICIO_COMP						THEN '23:59:59' END
	)
	INSERT INTO @TABELA_TEMPO_COMP (SEQ, TEMPO)
	SELECT SEQ, TEMPO
		FROM CTE1B
		OPTION (MAXRECURSION 32767)
END


IF NOT EXISTS (SELECT *
			FROM @TABELA_TEMPO_COMP A
			LEFT JOIN @TABELA_TEMPO B ON A.TEMPO = B.TEMPO
			WHERE B.TEMPO IS NULL)
BEGIN
	SET @FLG_TEMPO_SUBCONJUNTO = 1
END


RETURN @FLG_TEMPO_SUBCONJUNTO

--SELECT DBO.FN_COMPARA_RANGE_TIMES('17:00:00', '02:00:00', '19:00:00', '02:00:00')

END

