ALTER FUNCTION [dbo].[FN_REMOVE_PADRAO] (@PADRAO VARCHAR(MAX), @PALAVRA VARCHAR(MAX)) RETURNS VARCHAR(MAX) AS
BEGIN

	WHILE PATINDEX(@PADRAO, @PALAVRA) > 0
	BEGIN
		SET @PALAVRA = RTRIM(LTRIM(STUFF(@PALAVRA, PATINDEX(@PADRAO, @PALAVRA), 1, '')))
	END 

	RETURN @PALAVRA
END
