CREATE TABLE TMP_ONETO_TESTE_JOIN_RECURSIVO (
ID INT, DESCRITIVO VARCHAR(200), CHAVE_ESTRANGEIRA INT)


INSERT INTO TMP_ONETO_TESTE_JOIN_RECURSIVO
		  SELECT 1,'JOAO',NULL
UNION ALL SELECT 2,'MARIA',1
UNION ALL SELECT 3,'AVELAR',2
UNION ALL SELECT 4,'CELUTA',3
UNION ALL SELECT 5,'MARIETA',4
UNION ALL SELECT 6,'MARINHO',NULL
UNION ALL SELECT 7,'CLAUDIO',6
UNION ALL SELECT 8,'VERGARA',NULL
UNION ALL SELECT 9,'VELAZQUES',6
UNION ALL SELECT 10,'MARCO',9
UNION ALL SELECT 11,'JULIANA',10
UNION ALL SELECT 12,'JACQUELINE',13
UNION ALL SELECT 13,'LARISSA',NULL


BEGIN
	WITH CTE AS (
	SELECT * FROM TMP_ONETO_TESTE_JOIN_RECURSIVO --WHERE CHAVE_ESTRANGEIRA IS NOT NULL
	UNION ALL
	SELECT A.ID, A.DESCRITIVO, B.CHAVE_ESTRANGEIRA  FROM TMP_ONETO_TESTE_JOIN_RECURSIVO A
		INNER JOIN CTE B ON A.CHAVE_ESTRANGEIRA = B.ID
	)
	SELECT DISTINCT ID, DESCRITIVO, CHAVE_ESTRANGEIRA_MENOR = MIN(CHAVE_ESTRANGEIRA) 
		FROM CTE 
		GROUP BY ID, DESCRITIVO
		ORDER BY 1
END




